import { useEffect, useRef, useState } from "react";
import {
  X,
  Sparkles,
  RefreshCw,
  Target,
  Layers,
  Lightbulb,
  Wrench,
  AlertTriangle,
  Link2,
  HelpCircle,
  BookOpen,
  Copy,
  Check,
  Download,
} from "lucide-react";
import { getConceptContent } from "../api/client";
import Markdown from "./Markdown";
import { exportAnswerAsPdf } from "../utils/pdfExport";
import "./Markdown.css";
import "./ConceptModal.css";

/**
 * Turn a raw backend error into a short, friendly message.
 */
function cleanErrorMessage(err) {
  const detail =
    err?.response?.data?.detail || err?.message || "Something went wrong.";
  const lower = String(detail).toLowerCase();

  if (lower.includes("unique") || lower.includes("duplicate")) {
    return "Content was being generated by another request. Please click Retry.";
  }
  if (lower.includes("json") && lower.includes("valid")) {
    return "The AI returned an unusual response. Please click Retry.";
  }
  if (lower.includes("timeout")) {
    return "Generation took too long. Please click Retry.";
  }
  if (lower.includes("rate") || lower.includes("429")) {
    return "Too many requests. Please wait a moment and click Retry.";
  }

  return "We couldn't generate this concept right now. Please try again.";
}

export default function ConceptModal({ concept, onClose }) {
  const [content, setContent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);
  const [error, setError] = useState("");
  const [copiedAll, setCopiedAll] = useState(false);
  const [exporting, setExporting] = useState(false);

  const bodyRef = useRef(null);

  useEffect(() => {
    if (!concept) return;
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [concept?.id]);

  useEffect(() => {
    const handleKey = (e) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", handleKey);
    return () => document.removeEventListener("keydown", handleKey);
  }, [onClose]);

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const res = await getConceptContent(concept.id);
      setContent(res.data.content);
    } catch (err) {
      setError(cleanErrorMessage(err));
    } finally {
      setLoading(false);
    }
  };

  const regenerate = async () => {
    setRegenerating(true);
    setError("");
    try {
      const res = await getConceptContent(concept.id, true);
      setContent(res.data.content);
    } catch (err) {
      setError(cleanErrorMessage(err));
    } finally {
      setRegenerating(false);
    }
  };

  const handleCopyAll = async () => {
    if (!bodyRef.current) return;
    try {
      await navigator.clipboard.writeText(bodyRef.current.innerText);
      setCopiedAll(true);
      setTimeout(() => setCopiedAll(false), 2000);
    } catch {
      setError("Could not copy.");
    }
  };

  const handleExportPdf = async () => {
    if (!bodyRef.current) return;
    setExporting(true);
    try {
      await exportAnswerAsPdf({
        title: concept?.name || "Concept",
        subtitle: "Concept Deep-Dive",
        sourceElement: bodyRef.current,
        filename: `${
          concept?.name?.replace(/\s+/g, "-").toLowerCase() || "concept"
        }.pdf`,
      });
    } catch (err) {
      console.error(err);
      setError("PDF export failed.");
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="concept-modal-backdrop" onClick={onClose}>
      <div
        className="concept-modal"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
      >
        {/* HEADER */}
        <div className="concept-modal-header">
          <div className="concept-modal-title-wrap">
            <div className="concept-modal-icon">
              <Sparkles size={18} />
            </div>
            <div>
              <div className="concept-modal-label">Concept Deep-Dive</div>
              <h2 className="concept-modal-title">{concept.name}</h2>
            </div>
          </div>

          <button
            className="concept-modal-close"
            onClick={onClose}
            aria-label="Close"
          >
            <X size={20} />
          </button>
        </div>

        {/* BODY */}
        <div className="concept-modal-body" ref={bodyRef}>
          {loading && (
            <div className="concept-modal-loading">
              <div className="loading-spinner">
                <Sparkles size={24} />
              </div>
              <p>Preparing concept breakdown...</p>
              <p className="concept-modal-hint">Takes about 4–8 seconds.</p>
            </div>
          )}

          {error && !loading && (
            <div className="concept-modal-error">
              <div className="concept-modal-error-row">
                <AlertTriangle size={18} />
                <p>{error}</p>
              </div>
              <div className="concept-modal-error-actions">
                <button className="btn-primary" onClick={load}>
                  <RefreshCw size={14} /> Retry
                </button>
                <button className="btn-secondary" onClick={onClose}>
                  Close
                </button>
              </div>
            </div>
          )}

          {!loading && !error && content && (
            <>
              <section className="cm-section">
                <div className="cm-section-head">
                  <Sparkles size={15} />
                  <h3>Summary</h3>
                </div>
                <p className="cm-text cm-summary">{content.summary}</p>
              </section>

              <section className="cm-section">
                <div className="cm-section-head">
                  <Target size={15} />
                  <h3>Why It Matters</h3>
                </div>
                <p className="cm-text">{content.why_it_matters}</p>
              </section>

              <section className="cm-section">
                <div className="cm-section-head">
                  <BookOpen size={15} />
                  <h3>Deep Explanation</h3>
                </div>
                <p className="cm-text">{content.deep_explanation}</p>
              </section>

              {content.how_it_works?.length > 0 && (
                <section className="cm-section">
                  <div className="cm-section-head">
                    <Layers size={15} />
                    <h3>How It Works</h3>
                  </div>
                  <ol className="cm-steps">
                    {content.how_it_works.map((s, i) => (
                      <li key={i}>
                        <span className="cm-step-num">{i + 1}</span>
                        <span>{s}</span>
                      </li>
                    ))}
                  </ol>
                </section>
              )}

              {content.intuition && (
                <section className="cm-section">
                  <div className="cm-section-head">
                    <Lightbulb size={15} />
                    <h3>Intuition</h3>
                  </div>
                  <p className="cm-text cm-intuition">{content.intuition}</p>
                </section>
              )}

              {content.concrete_example && (
                <section className="cm-section">
                  <div className="cm-section-head">
                    <Wrench size={15} />
                    <h3>Concrete Example</h3>
                  </div>
                  <div className="cm-example-wrap">
                    <Markdown>{content.concrete_example}</Markdown>
                  </div>
                </section>
              )}

              {content.common_pitfalls?.length > 0 && (
                <section className="cm-section">
                  <div className="cm-section-head">
                    <AlertTriangle size={15} />
                    <h3>Common Pitfalls</h3>
                  </div>
                  <ul className="cm-list cm-pitfalls">
                    {content.common_pitfalls.map((p, i) => (
                      <li key={i}>{p}</li>
                    ))}
                  </ul>
                </section>
              )}

              {content.connections?.length > 0 && (
                <section className="cm-section">
                  <div className="cm-section-head">
                    <Link2 size={15} />
                    <h3>Related Concepts</h3>
                  </div>
                  <div className="cm-chips">
                    {content.connections.map((c, i) => (
                      <span key={i} className="cm-chip">
                        {c}
                      </span>
                    ))}
                  </div>
                </section>
              )}

              {content.quick_check && (
                <section className="cm-section cm-quick-check">
                  <div className="cm-section-head">
                    <HelpCircle size={15} />
                    <h3>Quick Check</h3>
                  </div>
                  <p className="cm-text">{content.quick_check}</p>
                </section>
              )}
            </>
          )}
        </div>

        {/* FOOTER */}
        {!loading && !error && content && (
          <div className="concept-modal-footer">
            <button className="btn-secondary" onClick={onClose}>
              Close
            </button>
            <button className="btn-secondary" onClick={handleCopyAll}>
              {copiedAll ? (
                <>
                  <Check size={14} /> Copied!
                </>
              ) : (
                <>
                  <Copy size={14} /> Copy
                </>
              )}
            </button>
            <button
              className="btn-secondary"
              onClick={handleExportPdf}
              disabled={exporting}
            >
              {exporting ? (
                <>
                  <RefreshCw size={14} className="spin" /> Preparing...
                </>
              ) : (
                <>
                  <Download size={14} /> PDF
                </>
              )}
            </button>
            <button
              className="btn-primary"
              onClick={regenerate}
              disabled={regenerating}
            >
              <RefreshCw size={14} className={regenerating ? "spin" : ""} />
              {regenerating ? "Regenerating..." : "Regenerate"}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}